

CREATE TABLE c1(
   ID    INTEGER NOT NULL PRIMARY KEY,
   DATA  TEXT    NOT NULL
);

CREATE SEQUENCE seq1
    INCREMENT 50
    START 1
    ;

CREATE TABLE C2(
   ID    INTEGER   NOT NULL PRIMARY KEY,
   DATA  TEXT      NOT NULL
);

CREATE SEQUENCE seq2
    INCREMENT 50
    START 1
    ;
COMMIT;

CREATE TABLE C3(
   ID    BIGSERIAL NOT NULL PRIMARY KEY,
   DATA  TEXT      NOT NULL
);

CREATE TABLE C4(
   ID    BIGSERIAL NOT NULL PRIMARY KEY,
   DATA  TEXT      NOT NULL
);

-- CREATE SEQUENCE hibernate_sequence START 1;
